services:
  - type: web
    name: tbjja
    env: static
    staticPublishPath: public
    routes:
      - type: rewrite
        source: /timetable
        destination: /timetable/index.html
      - type: rewrite
        source: /memberships
        destination: /memberships/index.html
